import { bigint, date, text, timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Column factories shared by every table module.
 *
 * Each factory returns a fresh builder on every call: a Drizzle column builder
 * is mutated while the table is assembled, so a shared instance would be
 * attached to more than one table.
 *
 * Column names are spelled out here even though the Drizzle client applies
 * `casing: 'snake_case'`. An explicit name is unaffected by configuration, so
 * the schema and the generated SQL cannot drift apart.
 */

/** Surrogate primary key: UUID v4 generated by PostgreSQL (`gen_random_uuid`). */
export function primaryId() {
  return uuid('id').primaryKey().defaultRandom();
}

/**
 * `created_at` / `updated_at` on every row that has a lifecycle.
 *
 * `updated_at` is maintained by the `wervi_touch_updated_at()` trigger from the
 * custom migration, not by the application: a raw `UPDATE`, a future admin tool
 * or an analytics script must not be able to leave a stale timestamp behind.
 */
export function createdAt() {
  return timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
}

export function updatedAt() {
  return timestamp('updated_at', { withTimezone: true }).notNull().defaultNow();
}

/** Optional soft-delete marker. A deleted row keeps its history and references. */
export function deletedAt() {
  return timestamp('deleted_at', { withTimezone: true });
}

export function optionalTimestamp(name: string) {
  return timestamp(name, { withTimezone: true });
}

export function requiredTimestamp(name: string) {
  return timestamp(name, { withTimezone: true }).notNull();
}

/** Calendar date with no time component, e.g. a delivery due date. */
export function dateOnly(name: string) {
  return date(name);
}

/**
 * Money as an integer count of minor units (cents, yen, fils), never a float.
 *
 * `bigint` rather than `integer`: a contract total in a three-decimal currency
 * such as BHD passes 2^31 minor units long before it reaches a million dollars,
 * and an int4 column would overflow instead of rejecting the amount.
 */
export function minorUnits(name: string) {
  return bigint(name, { mode: 'number' });
}

/** ISO 4217 code. Always paired with a minor-unit column. */
export function currencyCode() {
  return text('currency');
}

/**
 * A closed vocabulary stored as `text` plus a CHECK constraint generated from
 * the shared constant list, so the database and the TypeScript type can never
 * disagree. Defaults to the first value, which is the natural initial state.
 */
export function enumColumn<const T extends readonly [string, ...string[]]>(
  name: string,
  values: T,
) {
  return text(name).$type<T[number]>().notNull().default(values[0]);
}

/**
 * Same vocabulary, but genuinely unknown until a user supplies it.
 *
 * The list is not used to build a default, only to constrain the type, so the
 * parameter is underscore-prefixed: it still exists because callers get the
 * vocabulary checked at compile time from the same shared list.
 */
export function optionalEnumColumn<
  const T extends readonly [string, ...string[]],
>(name: string, _values: T) {
  return text(name).$type<T[number]>();
}

/** Short human-authored text: names, slugs, headlines, currency codes. */
export function shortText(name: string) {
  return text(name);
}

/** Long human-authored or machine-generated text: descriptions, letters. */
export function longText(name: string) {
  return text(name);
}
